insert into place(name) values('Lisboa')
insert into place(name) values('Madrid')
insert into route(fk_origin,fk_destination) values (1,2)
insert into route(fk_origin,fk_destination) values (2,1)
insert into company(name,allow_luggage) values ('AirFrance',true)
insert into flight(arrival_date,arrival_time,departure_date,departure_time,fk_route,fk_company) values ('2022-11-06','10:00:00','2022-11-06','09:00:00',1,1)
insert into groups_age(group_age) values ('<2')
insert into groups_age(group_age) values ('>2<9')
insert into groups_age(group_age) values ('>9')
insert into price (price,additional_cost,fk_flight,fk_groups_age) values (200.0,30.0,1,2)


--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-02',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-03',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-04',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-05',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-06',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-07',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-08',1,1)
--insert into flight(departure_date,fk_route,fk_company) values ('2022-11-09',1,1)